replicaCount: 1

image:
  repository: ghcr.io/mlflow/mlflow
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: mlflow.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /mlflow

environment:
  MLFLOW_BACKEND_STORE_URI: "file:///mlflow/mlruns"
  MLFLOW_DEFAULT_ARTIFACT_ROOT: "/mlflow/artifacts"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
